### ISSUE TITLE
Make subclassing and customizations easier

### ISSUE THREAD

**Issue by n1schal** [hmhv/SoftUIView#1]
Hey, wonderful take on the SoftUI

I have one request, would you mind making the class open so that we could make reusable buttons instead of having to create and setup each instance separately? 

Thanks a ton for the amazing work BTW

**Comment by hmhv** [comment]
Thank you!
I made the class open. check version 0.0.2.

**Comment by n1schal** [comment]
thanks! will try i t out. a suggestion though, i think you could allow setting two different shadow styles for selected v normal states so that we wouldn't have to configure them again through the tap handler.

**Comment by hmhv** [comment]
If you have any more idea, make Pull request. :-)
